version: '3'

services:
  tcdd-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=8080
      # These will be loaded from .env file or set directly in the environment
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      # Optional: Auto-setup webhook on startup
      - AUTO_SETUP_WEBHOOK=${AUTO_SETUP_WEBHOOK:-false}
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
